version: '3'
services:
  spark-master:
    image: bitnami/spark:3.3.2
    user: root 
    container_name: spark-master
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master Port
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-app:/app

  spark-worker-1:
    image: bitnami/spark:3.3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark-app:/app

  spark-worker-2:
    image: bitnami/spark:3.3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark-app:/app

  jupyter:
    image: jupyter/pyspark-notebook:python-3.9
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - SPARK_HOME=/usr/local/spark
    command: start-notebook.sh --NotebookApp.token='asdf'
